# Generated by Django 4.2.1 on 2023-10-08 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0002_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 9, 22, 33, 891066, tzinfo=datetime.timezone.utc)),
        ),
    ]
