# Generated by Django 4.2.1 on 2023-10-08 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0005_rename_original_assigned_to_ids_archivedproject_original_assigned_to_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 14, 9, 55, 661719, tzinfo=datetime.timezone.utc)),
        ),
    ]
