# Generated by Django 4.2.1 on 2023-10-15 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0007_alter_passwordresettoken_expires_at_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('student_application', 'Student Applications'), ('supervisor_evaluation', 'Supervisor Evaluations'), ('semester_changed', 'Previous Project List'), ('panel_project', 'Project'), ('panel_presentation', 'Panel Presentation'), ('panel_evaluation', 'Panel Evaluation'), ('student_project', 'Student Project'), ('panel_assigned', 'Student Project'), ('student_presentation', 'Student Presentation')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 10, 42, 11, 211706, tzinfo=datetime.timezone.utc)),
        ),
    ]
