# Generated by Django 4.2.1 on 2023-10-20 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0010_alter_passwordresettoken_expires_at_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demosubmission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='demosubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='presentationsubmission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='presentationsubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='proposalsubmission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='proposalsubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='reportsubmission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reportsubmission',
            name='student',
        ),
        migrations.AddField(
            model_name='submission',
            name='uploaded_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 13, 43, 809500, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('PROPOSAL', 'Proposal'), ('REPORT', 'Report'), ('PRESENTATION', 'Presentation'), ('DEMO', 'Demo'), ('DATA_PRODUCT', 'Data Product')], default='PROPOSAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='submission',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.DeleteModel(
            name='DataProductSubmission',
        ),
        migrations.DeleteModel(
            name='DemoSubmission',
        ),
        migrations.DeleteModel(
            name='PresentationSubmission',
        ),
        migrations.DeleteModel(
            name='ProposalSubmission',
        ),
        migrations.DeleteModel(
            name='ReportSubmission',
        ),
    ]
