# Generated by Django 4.2.1 on 2023-10-20 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0011_remove_demosubmission_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 30, 45, 952436, tzinfo=datetime.timezone.utc)),
        ),
    ]
