# Generated by Django 4.2.1 on 2023-10-24 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0016_criteria_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 17, 40, 33405, tzinfo=datetime.timezone.utc)),
        ),
    ]
