# Generated by Django 4.2.1 on 2023-10-26 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0019_alter_panelmonitoring_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 11, 20, 23, 870826, tzinfo=datetime.timezone.utc)),
        ),
    ]
