# Generated by Django 4.2.1 on 2023-10-26 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0021_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 17, 1, 7, 902938, tzinfo=datetime.timezone.utc)),
        ),
    ]
