# Generated by Django 4.2.1 on 2023-10-27 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0022_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('student_application', 'Student Applications'), ('supervisor_evaluation_proposal', 'Proposal Evaluations'), ('supervisor_evaluation_report', 'Report Evaluations'), ('supervisor_evaluation_presentation', 'Presentation Evaluations'), ('supervisor_evaluation_demo', 'Demo Evaluations'), ('supervisor_evaluation_data_product', 'Data Product Evaluations'), ('semester_changed', 'Change Semester'), ('panel_project', 'Get Panel Project'), ('panel_presentation', 'Panel Presentation Slot'), ('panel_evaluation_score', 'Panel Evaluation'), ('panel_evaluation_presentation', 'Panel Evaluation'), ('panel_evaluation_demo', 'Panel Evaluation'), ('panel_evaluation_data_product', 'Panel Evaluation'), ('panel_score_difference', 'Panel Evaluation'), ('student_project', 'Student Project'), ('student_presentation', 'Student Presentation Slot'), ('student_monitoring', 'Student Monitoring Evaluation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 5, 22, 6, 226564, tzinfo=datetime.timezone.utc)),
        ),
    ]
