# Generated by Django 4.2.1 on 2023-10-27 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0023_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 5, 22, 17, 635462, tzinfo=datetime.timezone.utc)),
        ),
    ]
