# Generated by Django 4.2.1 on 2023-10-29 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0025_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supervisorevaluation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 9, 1, 49, 87571, tzinfo=datetime.timezone.utc)),
        ),
    ]
