# Generated by Django 4.2.1 on 2023-11-03 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0027_remove_panelmonitoring_criteria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataProductSubmission',
            new_name='GoogleDriveSubmission',
        ),
        migrations.RemoveField(
            model_name='presentationsubmission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='presentationsubmission',
            name='student',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 9, 54, 4, 594368, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='DemoSubmission',
        ),
        migrations.DeleteModel(
            name='PresentationSubmission',
        ),
    ]
