# Generated by Django 4.2.1 on 2023-11-03 10:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0028_rename_dataproductsubmission_googledrivesubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationschedule',
            name='coordinator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_presentation_schedules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 11, 33, 22, 966223, tzinfo=datetime.timezone.utc)),
        ),
    ]
