# Generated by Django 4.2.1 on 2023-11-03 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0029_presentationschedule_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 11, 34, 10, 406707, tzinfo=datetime.timezone.utc)),
        ),
    ]
