# Generated by Django 4.2.1 on 2023-11-03 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0030_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 14, 21, 16, 788076, tzinfo=datetime.timezone.utc)),
        ),
    ]
