# Generated by Django 4.2.1 on 2023-11-10 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0034_alter_passwordresettoken_expires_at_timerange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerange',
            old_name='user',
            new_name='panel',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 16, 2, 17, 91406, tzinfo=datetime.timezone.utc)),
        ),
    ]
