# Generated by Django 4.2.1 on 2023-11-10 16:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0035_rename_user_timerange_panel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 17, 4, 24, 887524, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timerange',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel', to=settings.AUTH_USER_MODEL),
        ),
    ]
