# Generated by Django 4.2.1 on 2023-11-13 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0036_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 9, 4, 33, 478003, tzinfo=datetime.timezone.utc)),
        ),
    ]
