# Generated by Django 4.2.1 on 2023-11-29 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0037_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 9, 14, 5, 311693, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='LecturerStudentLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_students', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_limits', to='dsmanagementapp.semester')),
            ],
        ),
    ]
