# Generated by Django 4.2.1 on 2023-11-30 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0038_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 12, 47, 5, 749431, tzinfo=datetime.timezone.utc)),
        ),
    ]
