# Generated by Django 4.2.1 on 2023-11-30 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0039_semester_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 13, 42, 18, 750641, tzinfo=datetime.timezone.utc)),
        ),
    ]
