# Generated by Django 4.2.1 on 2023-11-30 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0040_semester_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 14, 22, 7, 343944, tzinfo=datetime.timezone.utc)),
        ),
    ]
