# Generated by Django 4.2.1 on 2023-12-01 02:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0042_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerange',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timerange',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timerange',
            name='time_slot',
            field=models.CharField(choices=[('9-11am', '9-11am'), ('11-1pm', '11-1pm'), ('2-4pm', '2-4pm'), ('4-6pm', '4-6pm')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 3, 30, 32, 465419, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timerange',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_ranges', to=settings.AUTH_USER_MODEL),
        ),
    ]
