# Generated by Django 4.2.1 on 2023-12-01 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0043_remove_timerange_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('9-11am', '9-11am'), ('11-1pm', '11-1pm'), ('2-4pm', '2-4pm'), ('4-6pm', '4-6pm')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='timerange',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 5, 8, 25, 607009, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='timerange',
            name='time_slots',
            field=models.ManyToManyField(to='dsmanagementapp.singletimeslot'),
        ),
    ]
