# Generated by Django 4.2.1 on 2023-12-01 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0044_singletimeslot_remove_timerange_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 13, 10, 32, 364082, tzinfo=datetime.timezone.utc)),
        ),
    ]
