# Generated by Django 4.2.1 on 2023-12-02 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0045_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 11, 28, 8, 531569, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='singletimeslot',
            name='slot',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9-11am'), (datetime.time(11, 0), '11-1pm'), (datetime.time(14, 0), '2-4pm'), (datetime.time(16, 0), '4-6pm')], default=None, unique=True),
        ),
    ]
