# Generated by Django 4.2.1 on 2023-12-02 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0046_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 11, 28, 31, 679223, tzinfo=datetime.timezone.utc)),
        ),
    ]
