# Generated by Django 4.2.1 on 2024-01-15 10:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanagementapp', '0049_alter_passwordresettoken_expires_at_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='semester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='semester_announcements', to='dsmanagementapp.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 11, 17, 24, 504321, tzinfo=datetime.timezone.utc)),
        ),
    ]
